/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package project_gui_draft2;

import java.io.*;
import java.util.Date;
import java.util.Map;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 * ReportController - manages interactions between Report models and the GUI
 */
public class ReportController {
    
    /**
     * Generates a sales report for a time period
     * @param adminId ID of the administrator generating the report
     * @param startDate Start date for the report period
     * @param endDate End date for the report period
     * @return Report object if generation succeeds, null otherwise
     */
    public static Report generateSalesReport(String adminId, Date startDate, Date endDate) {
        Administrator admin = new Administrator(adminId, "", "", "");
        return admin.generateSalesReport(startDate, endDate);
    }
    
    /**
     * Generates an inventory report
     * @param adminId ID of the administrator generating the report
     * @return Report object if generation succeeds, null otherwise
     */
    public static Report generateInventoryReport(String adminId) {
        Administrator admin = new Administrator(adminId, "", "", "");
        return admin.generateInventoryReport();
    }
    
    /**
     * Generates a spending report for a customer
     * @param customerId ID of the customer
     * @return Map containing spending statistics
     */
    public static Map<String, Object> generateCustomerSpendingReport(String customerId) {
        Customer customer = new Customer(customerId, "", "", "");
        return customer.generateStatistics();
    }
    
    /**
     * Generates a contribution report for a supplier
     * @param supplierId ID of the supplier
     * @return Map containing contribution statistics
     */
    public static Map<String, Object> generateSupplierContributionReport(String supplierId) {
        Supplier supplier = new Supplier(supplierId, "", "", "");
        return supplier.getContributionStats();
    }
    
     /**
     * Exports a report to a text file
     * Note: This creates a plain text report, not an actual PDF
     * @param report Report to export
     * @param file File to export to
     * @return true if export succeeds, false otherwise
     */
    public static boolean exportReportToFile(Report report, File file) {
        try {
            // Make sure the file has .txt extension
            File outputFile = file;
            String fileName = file.getName();

            // If file ends with .pdf, replace it with .txt
            if (fileName.toLowerCase().endsWith(".pdf")) {
                String newName = fileName.substring(0, fileName.length() - 4) + ".txt";
                outputFile = new File(file.getParentFile(), newName);
            }

            // Use FileWriter with the correct file
            try (FileWriter writer = new FileWriter(outputFile)) {
                // Create a properly formatted report
                StringBuilder content = new StringBuilder();

                // Header with title and date
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                content.append("===================================================\n");
                content.append("                 ").append(report.getTitle()).append("\n");
                content.append("===================================================\n\n");
                content.append("Generated: ").append(dateFormat.format(new Date())).append("\n");
                content.append("Report Type: ").append(report.getReportType()).append("\n");
                content.append("Generated By: ").append(report.getGeneratorName()).append("\n\n");
                content.append("===================================================\n\n");

                // Report data
                Map<String, Object> data = report.getDataContent();
                for (Map.Entry<String, Object> entry : data.entrySet()) {
                    String key = formatKey(entry.getKey());
                    Object value = entry.getValue();

                    if (value instanceof Map) {
                        content.append(key).append(":\n");
                        Map<?, ?> nestedMap = (Map<?, ?>)value;
                        for (Map.Entry<?, ?> nestedEntry : nestedMap.entrySet()) {
                            content.append("    - ").append(nestedEntry.getKey())
                                   .append(": ").append(nestedEntry.getValue()).append("\n");
                        }
                        content.append("\n");
                    } else if (value instanceof Double) {
                        // Format currency values
                        if (key.toLowerCase().contains("revenue") || 
                            key.toLowerCase().contains("amount") || 
                            key.toLowerCase().contains("value")) {
                            content.append(key).append(": $").append(String.format("%.2f", value)).append("\n");
                        } else {
                            content.append(key).append(": ").append(value).append("\n");
                        }
                    } else {
                        content.append(key).append(": ").append(value).append("\n");
                    }
                }

                // Write the content to the file
                writer.write(content.toString());

                // Show success message with the actual file path
                JOptionPane.showMessageDialog(null,
                    "Report exported successfully to:\n" + outputFile.getAbsolutePath(),
                    "Export Complete",
                    JOptionPane.INFORMATION_MESSAGE);

                return true;
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,
                "Error exporting report: " + e.getMessage(),
                "Export Error",
                JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    /**
     * Helper method to format keys for display
     * (Convert camelCase to Title Case)
     */
    private static String formatKey(String key) {
        if (key == null || key.isEmpty()) {
            return "";
        }

        StringBuilder result = new StringBuilder();

        // Handle first character
        result.append(Character.toUpperCase(key.charAt(0)));

        // Handle the rest, adding space before capital letters
        for (int i = 1; i < key.length(); i++) {
            char c = key.charAt(i);
            if (Character.isUpperCase(c)) {
                result.append(' ').append(c);
            } else {
                result.append(c);
            }
        }

        return result.toString();
    }
    
    /**
     * Gets most popular books for a time period
     * @param startDate Start date
     * @param endDate End date
     * @param limit Maximum number of books to return
     * @return Array of book titles ordered by popularity
     */
    public static String[] getMostPopularBooks(Date startDate, Date endDate, int limit) {
        java.sql.Connection conn = DatabaseConnector.getInstance().getConnection();
        java.util.List<String> popularBooks = new java.util.ArrayList<>();
        
        try {
            String sql = "SELECT b.title, SUM(oi.quantity) as total " +
                         "FROM order_items oi " +
                         "JOIN orders o ON oi.order_id = o.order_id " +
                         "JOIN books b ON oi.book_id = b.book_id " +
                         "WHERE o.order_date BETWEEN ? AND ? " +
                         "GROUP BY b.title " +
                         "ORDER BY total DESC " +
                         "LIMIT ?";
                         
            java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setDate(1, new java.sql.Date(startDate.getTime()));
            stmt.setDate(2, new java.sql.Date(endDate.getTime()));
            stmt.setInt(3, limit);
            
            java.sql.ResultSet rs = stmt.executeQuery();
            
            while (rs.next()) {
                popularBooks.add(rs.getString("title"));
            }
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
        }
        
        return popularBooks.toArray(new String[0]);
    }
    
    /**
     * Gets monthly revenue data for charting
     * @param year Year to get data for
     * @return Array of monthly revenue values
     */
    public static double[] getMonthlyRevenueData(int year) {
        double[] monthlyRevenue = new double[12];
        java.sql.Connection conn = DatabaseConnector.getInstance().getConnection();
        
        try {
            String sql = "SELECT MONTH(order_date) as month, SUM(total_amount) as revenue " +
                         "FROM orders " +
                         "WHERE YEAR(order_date) = ? AND status = 'Completed' " +
                         "GROUP BY MONTH(order_date)";
                         
            java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setInt(1, year);
            
            java.sql.ResultSet rs = stmt.executeQuery();
            
            while (rs.next()) {
                int month = rs.getInt("month");
                double revenue = rs.getDouble("revenue");
                // Month is 1-based in database, but array is 0-based
                monthlyRevenue[month - 1] = revenue;
            }
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
        }
        
        return monthlyRevenue;
    }
    
    /**
     * Gets sales breakdown by genre
     * @param startDate Start date
     * @param endDate End date
     * @return Map of genre to sales count
     */
    public static Map<String, Integer> getGenreSalesBreakdown(Date startDate, Date endDate) {
        Map<String, Integer> genreSales = new java.util.HashMap<>();
        java.sql.Connection conn = DatabaseConnector.getInstance().getConnection();
        
        try {
            String sql = "SELECT b.genre, SUM(oi.quantity) as total " +
                         "FROM order_items oi " +
                         "JOIN orders o ON oi.order_id = o.order_id " +
                         "JOIN books b ON oi.book_id = b.book_id " +
                         "WHERE o.order_date BETWEEN ? AND ? " +
                         "GROUP BY b.genre";
                         
            java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setDate(1, new java.sql.Date(startDate.getTime()));
            stmt.setDate(2, new java.sql.Date(endDate.getTime()));
            
            java.sql.ResultSet rs = stmt.executeQuery();
            
            while (rs.next()) {
                genreSales.put(rs.getString("genre"), rs.getInt("total"));
            }
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
        }
        
        return genreSales;
    }
    
}
